permalink:  /:year/:month/:title/
baseurl:    /blog

title:      Leonard Ehrenfried's notebook
author:     Leonard Ehrenfried

url:        http://leonard.io/blog

feed_base:  http://lenni.info/blog

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
theme:      jekyll-whiteglass
paginate:   5
comments:   true


