permalink:  /:year/:month/:title/
baseurl:    /blog
url:        http://leonard.io/blog
feed_base:  http://lenni.info/blog
plugins:    [jekyll-paginate, redcarpet]
paginate:   5
markdown:   redcarpet
redcarpet:
  extensions: [smart]

