permalink:  /:year/:month/:title/
baseurl:    /blog

title:      Leonard Ehrenfried's notebook
author:     Leonard Ehrenfried

url:        http://leonard.io

feed:
  path: feed.xml

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

theme:      jekyll-whiteglass
paginate:   5
comments:   true


